version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.14
    steps:
      - checkout
      - run:
          name: Install firefox 38.0.5
          command: |
            FIREFOX_URL="https://sourceforge.net/projects/ubuntuzilla/files/mozilla/apt/pool/main/f/firefox-mozilla-build/firefox-mozilla-build_38.0.5-0ubuntu1_amd64.deb/download" \
            && sudo apt-get update \
            && curl --silent --show-error --location --fail --retry 3 --output /tmp/firefox.deb $FIREFOX_URL \
            && sudo dpkg -i /tmp/firefox.deb || sudo apt-get -f install  \
            && sudo apt-get install -y libgtk3.0-cil-dev libasound2 libasound2 libdbus-glib-1-2 libdbus-1-3 libgtk2.0-0 \
            && rm -rf /tmp/firefox.deb \
            && firefox --version
      - run:
          name: Run tests
          command: |
            virtualenv venv && venv/bin/pip install tox && venv/bin/tox

  deploy:
    docker:
      - image: circleci/python:2.7.14
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "circle.yml" }}-{{ checksum "setup.py" }}
      - run:
          name: Install dependencies
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install -U pip twine wheel
      - save_cache:
          key: dependencies-{{ checksum "circle.yml" }}-{{ checksum "setup.py" }}
          paths:
            - "venv"
      - run:
          name: Verify commit is tagged and tag matches version
          command: |
            . venv/bin/activate
            python setup.py verify_tag
      - run:
          name: Initialize .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = opencraft" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: Create packages
          command: |
            python setup.py sdist
            python setup.py bdist_wheel
      - run:
          name: Upload to pypi
          command: |
            . venv/bin/activate
            twine upload dist/*

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
